// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AckAlarm(arg1) {
  return window['go']['main']['App']['AckAlarm'](arg1);
}

export function AddKnowledge(arg1, arg2) {
  return window['go']['main']['App']['AddKnowledge'](arg1, arg2);
}

export function BatchDeleteVariables(arg1) {
  return window['go']['main']['App']['BatchDeleteVariables'](arg1);
}

export function BatchRegenerateShiftSnapshots(arg1, arg2, arg3) {
  return window['go']['main']['App']['BatchRegenerateShiftSnapshots'](arg1, arg2, arg3);
}

export function BatchUpdateVariables(arg1) {
  return window['go']['main']['App']['BatchUpdateVariables'](arg1);
}

export function CheckAIServiceHealth() {
  return window['go']['main']['App']['CheckAIServiceHealth']();
}

export function CreateOrder(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateOrder'](arg1, arg2, arg3, arg4);
}

export function CreateStaff(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateStaff'](arg1, arg2, arg3);
}

export function CreateTask(arg1) {
  return window['go']['main']['App']['CreateTask'](arg1);
}

export function CreateTeam(arg1, arg2) {
  return window['go']['main']['App']['CreateTeam'](arg1, arg2);
}

export function CreateVariable(arg1) {
  return window['go']['main']['App']['CreateVariable'](arg1);
}

export function DebugOEEByShift() {
  return window['go']['main']['App']['DebugOEEByShift']();
}

export function DebugOEEDirect() {
  return window['go']['main']['App']['DebugOEEDirect']();
}

export function DebugOEEProductionRaw() {
  return window['go']['main']['App']['DebugOEEProductionRaw']();
}

export function DeleteKnowledge(arg1) {
  return window['go']['main']['App']['DeleteKnowledge'](arg1);
}

export function DeleteKnowledgeBySource(arg1) {
  return window['go']['main']['App']['DeleteKnowledgeBySource'](arg1);
}

export function DeleteOrder(arg1) {
  return window['go']['main']['App']['DeleteOrder'](arg1);
}

export function DeleteStaff(arg1) {
  return window['go']['main']['App']['DeleteStaff'](arg1);
}

export function DeleteTask(arg1) {
  return window['go']['main']['App']['DeleteTask'](arg1);
}

export function DeleteTeam(arg1) {
  return window['go']['main']['App']['DeleteTeam'](arg1);
}

export function DeleteVariable(arg1) {
  return window['go']['main']['App']['DeleteVariable'](arg1);
}

export function DeviceLogin(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeviceLogin'](arg1, arg2, arg3);
}

export function DeviceLogout(arg1) {
  return window['go']['main']['App']['DeviceLogout'](arg1);
}

export function DisableTask(arg1) {
  return window['go']['main']['App']['DisableTask'](arg1);
}

export function EnableTask(arg1) {
  return window['go']['main']['App']['EnableTask'](arg1);
}

export function GetActiveAlarmCount() {
  return window['go']['main']['App']['GetActiveAlarmCount']();
}

export function GetActiveOrderQuality() {
  return window['go']['main']['App']['GetActiveOrderQuality']();
}

export function GetActiveSession(arg1) {
  return window['go']['main']['App']['GetActiveSession'](arg1);
}

export function GetAlarmRecords(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetAlarmRecords'](arg1, arg2, arg3, arg4);
}

export function GetAlarmStats() {
  return window['go']['main']['App']['GetAlarmStats']();
}

export function GetAllActiveSessions() {
  return window['go']['main']['App']['GetAllActiveSessions']();
}

export function GetAllDevices() {
  return window['go']['main']['App']['GetAllDevices']();
}

export function GetAllDevicesEnergyData() {
  return window['go']['main']['App']['GetAllDevicesEnergyData']();
}

export function GetAllDevicesStatus() {
  return window['go']['main']['App']['GetAllDevicesStatus']();
}

export function GetAllErrorCodes() {
  return window['go']['main']['App']['GetAllErrorCodes']();
}

export function GetAllGateways() {
  return window['go']['main']['App']['GetAllGateways']();
}

export function GetAllOrders() {
  return window['go']['main']['App']['GetAllOrders']();
}

export function GetAllShiftsOEESummary() {
  return window['go']['main']['App']['GetAllShiftsOEESummary']();
}

export function GetAllShiftsQualitySummary() {
  return window['go']['main']['App']['GetAllShiftsQualitySummary']();
}

export function GetAllStaff(arg1, arg2) {
  return window['go']['main']['App']['GetAllStaff'](arg1, arg2);
}

export function GetAllTags() {
  return window['go']['main']['App']['GetAllTags']();
}

export function GetAllTasks() {
  return window['go']['main']['App']['GetAllTasks']();
}

export function GetAllTeams(arg1) {
  return window['go']['main']['App']['GetAllTeams'](arg1);
}

export function GetAllVariables() {
  return window['go']['main']['App']['GetAllVariables']();
}

export function GetBreakTimes() {
  return window['go']['main']['App']['GetBreakTimes']();
}

export function GetChannelStats() {
  return window['go']['main']['App']['GetChannelStats']();
}

export function GetCurrentShift() {
  return window['go']['main']['App']['GetCurrentShift']();
}

export function GetDailyQualityByRun() {
  return window['go']['main']['App']['GetDailyQualityByRun']();
}

export function GetDailyWorkMinutes() {
  return window['go']['main']['App']['GetDailyWorkMinutes']();
}

export function GetDefaultShiftWindow() {
  return window['go']['main']['App']['GetDefaultShiftWindow']();
}

export function GetDeviceCycleTime(arg1) {
  return window['go']['main']['App']['GetDeviceCycleTime'](arg1);
}

export function GetDeviceStatusHistory(arg1) {
  return window['go']['main']['App']['GetDeviceStatusHistory'](arg1);
}

export function GetDeviceStatusHistoryAll(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetDeviceStatusHistoryAll'](arg1, arg2, arg3);
}

export function GetDeviceStatusStats() {
  return window['go']['main']['App']['GetDeviceStatusStats']();
}

export function GetDeviceUtilizationTrend(arg1) {
  return window['go']['main']['App']['GetDeviceUtilizationTrend'](arg1);
}

export function GetHistoryData(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['GetHistoryData'](arg1, arg2, arg3, arg4, arg5);
}

export function GetHourlyOEE() {
  return window['go']['main']['App']['GetHourlyOEE']();
}

export function GetHourlyProduction(arg1) {
  return window['go']['main']['App']['GetHourlyProduction'](arg1);
}

export function GetHourlyProductionAccurate(arg1) {
  return window['go']['main']['App']['GetHourlyProductionAccurate'](arg1);
}

export function GetKnowledgeList() {
  return window['go']['main']['App']['GetKnowledgeList']();
}

export function GetMonthlyDailyQualityTrend() {
  return window['go']['main']['App']['GetMonthlyDailyQualityTrend']();
}

export function GetMonthlyProductionAccurate(arg1) {
  return window['go']['main']['App']['GetMonthlyProductionAccurate'](arg1);
}

export function GetMonthlyQualityByOrder() {
  return window['go']['main']['App']['GetMonthlyQualityByOrder']();
}

export function GetRealHourlyProduction() {
  return window['go']['main']['App']['GetRealHourlyProduction']();
}

export function GetRealtimeData() {
  return window['go']['main']['App']['GetRealtimeData']();
}

export function GetScheduleDeviceIDs(arg1) {
  return window['go']['main']['App']['GetScheduleDeviceIDs'](arg1);
}

export function GetSessionHistory(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetSessionHistory'](arg1, arg2, arg3, arg4);
}

export function GetSessionStats(arg1) {
  return window['go']['main']['App']['GetSessionStats'](arg1);
}

export function GetShiftSchedules() {
  return window['go']['main']['App']['GetShiftSchedules']();
}

export function GetShiftSnapshots(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['GetShiftSnapshots'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function GetShifts() {
  return window['go']['main']['App']['GetShifts']();
}

export function GetShiftsForLogicalDay() {
  return window['go']['main']['App']['GetShiftsForLogicalDay']();
}

export function GetStaffAttendance(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetStaffAttendance'](arg1, arg2, arg3);
}

export function GetStaffEfficiency(arg1, arg2) {
  return window['go']['main']['App']['GetStaffEfficiency'](arg1, arg2);
}

export function GetStaffHistory(arg1) {
  return window['go']['main']['App']['GetStaffHistory'](arg1);
}

export function GetSystemConfig() {
  return window['go']['main']['App']['GetSystemConfig']();
}

export function GetSystemMonitor() {
  return window['go']['main']['App']['GetSystemMonitor']();
}

export function GetTodayEnergyConsumption(arg1) {
  return window['go']['main']['App']['GetTodayEnergyConsumption'](arg1);
}

export function GetTodayHourlyAlarmCount() {
  return window['go']['main']['App']['GetTodayHourlyAlarmCount']();
}

export function GetTodayUnacknowledgedAlarmCount() {
  return window['go']['main']['App']['GetTodayUnacknowledgedAlarmCount']();
}

export function GetVariableOptions() {
  return window['go']['main']['App']['GetVariableOptions']();
}

export function LikeAIAnswer(arg1, arg2, arg3) {
  return window['go']['main']['App']['LikeAIAnswer'](arg1, arg2, arg3);
}

export function QueryAI(arg1) {
  return window['go']['main']['App']['QueryAI'](arg1);
}

export function QueryAIStream(arg1) {
  return window['go']['main']['App']['QueryAIStream'](arg1);
}

export function QueryAIStreamWithQueue(arg1) {
  return window['go']['main']['App']['QueryAIStreamWithQueue'](arg1);
}

export function RegenerateShiftSnapshot(arg1, arg2, arg3) {
  return window['go']['main']['App']['RegenerateShiftSnapshot'](arg1, arg2, arg3);
}

export function SaveShiftSchedules(arg1) {
  return window['go']['main']['App']['SaveShiftSchedules'](arg1);
}

export function SetBreakTimes(arg1) {
  return window['go']['main']['App']['SetBreakTimes'](arg1);
}

export function SetDailyWorkMinutes(arg1) {
  return window['go']['main']['App']['SetDailyWorkMinutes'](arg1);
}

export function SetDeviceCycleTime(arg1, arg2) {
  return window['go']['main']['App']['SetDeviceCycleTime'](arg1, arg2);
}

export function SetDeviceSchedule(arg1, arg2) {
  return window['go']['main']['App']['SetDeviceSchedule'](arg1, arg2);
}

export function SetSystemConfig(arg1) {
  return window['go']['main']['App']['SetSystemConfig'](arg1);
}

export function StartProductionSmart(arg1) {
  return window['go']['main']['App']['StartProductionSmart'](arg1);
}

export function StopAIStream() {
  return window['go']['main']['App']['StopAIStream']();
}

export function SyncErrorCode(arg1, arg2) {
  return window['go']['main']['App']['SyncErrorCode'](arg1, arg2);
}

export function TransferStaff(arg1, arg2, arg3) {
  return window['go']['main']['App']['TransferStaff'](arg1, arg2, arg3);
}

export function TriggerTaskManually(arg1) {
  return window['go']['main']['App']['TriggerTaskManually'](arg1);
}

export function UpdateOrder(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpdateOrder'](arg1, arg2, arg3, arg4, arg5);
}

export function UpdateStaff(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateStaff'](arg1, arg2, arg3, arg4);
}

export function UpdateTask(arg1, arg2) {
  return window['go']['main']['App']['UpdateTask'](arg1, arg2);
}

export function UpdateTeam(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateTeam'](arg1, arg2, arg3, arg4);
}

export function UpdateVariable(arg1) {
  return window['go']['main']['App']['UpdateVariable'](arg1);
}
