// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {database} from '../models';
import {models} from '../models';
import {time} from '../models';

export function AckAlarm(arg1:number):Promise<void>;

export function AddKnowledge(arg1:string,arg2:any):Promise<main.AddKnowledgeResponse>;

export function BatchDeleteVariables(arg1:Array<number>):Promise<void>;

export function BatchUpdateVariables(arg1:Array<database.VariableRow>):Promise<void>;

export function CheckAIServiceHealth():Promise<boolean>;

export function CreateOrder(arg1:string,arg2:string,arg3:number,arg4:any):Promise<models.ProOrder>;

export function CreateStaff(arg1:string,arg2:string,arg3:any):Promise<models.SysStaff>;

export function CreateTask(arg1:models.Task):Promise<void>;

export function CreateTeam(arg1:string,arg2:any):Promise<models.SysTeam>;

export function CreateVariable(arg1:database.VariableRow):Promise<void>;

export function DebugOEEDirect():Promise<Record<string, any>>;

export function DebugOEEProductionRaw():Promise<Array<Record<string, any>>>;

export function DeleteKnowledge(arg1:string):Promise<main.DeleteKnowledgeResponse>;

export function DeleteKnowledgeBySource(arg1:string):Promise<main.DeleteKnowledgeResponse>;

export function DeleteOrder(arg1:number):Promise<void>;

export function DeleteStaff(arg1:number):Promise<void>;

export function DeleteTask(arg1:number):Promise<void>;

export function DeleteTeam(arg1:number):Promise<void>;

export function DeleteVariable(arg1:number):Promise<void>;

export function DeviceLogin(arg1:number,arg2:number,arg3:Array<number>):Promise<models.ProMachineSession>;

export function DeviceLogout(arg1:number):Promise<models.ProMachineSession>;

export function DisableTask(arg1:number):Promise<void>;

export function EnableTask(arg1:number):Promise<void>;

export function GetActiveAlarmCount():Promise<number>;

export function GetActiveOrderQuality():Promise<Array<database.DeviceQualityStat>>;

export function GetActiveSession(arg1:number):Promise<models.ProMachineSession>;

export function GetAlarmRecords(arg1:any,arg2:string,arg3:string,arg4:any):Promise<Array<main.AlarmRecordData>>;

export function GetAlarmStats():Promise<Record<string, any>>;

export function GetAllActiveSessions():Promise<Array<models.ProMachineSession>>;

export function GetAllDevices():Promise<Array<models.SysDevice>>;

export function GetAllDevicesEnergyData():Promise<Array<main.DeviceEnergyData>>;

export function GetAllDevicesStatus():Promise<Array<main.DeviceStatusData>>;

export function GetAllErrorCodes():Promise<Array<database.ErrorCode>>;

export function GetAllGateways():Promise<Array<main.Gateway>>;

export function GetAllOrders():Promise<Array<models.ProOrder>>;

export function GetAllStaff(arg1:any,arg2:any):Promise<Array<models.SysStaff>>;

export function GetAllTags():Promise<Array<main.TagInfo>>;

export function GetAllTasks():Promise<Array<models.Task>>;

export function GetAllTeams(arg1:any):Promise<Array<models.SysTeam>>;

export function GetAllVariables():Promise<Array<database.VariableRow>>;

export function GetBreakTimes():Promise<Array<main.BreakTime>>;

export function GetChannelStats():Promise<Record<string, number>>;

export function GetDailyQualityByRun():Promise<Array<database.DeviceQualityStat>>;

export function GetDailyWorkMinutes():Promise<number>;

export function GetDeviceStatusHistory(arg1:number):Promise<Array<models.SysDeviceStatus>>;

export function GetDeviceStatusHistoryAll(arg1:any,arg2:string,arg3:string):Promise<Array<main.DeviceStatusHistoryData>>;

export function GetDeviceStatusStats():Promise<Record<string, any>>;

export function GetDeviceUtilizationTrend(arg1:any):Promise<Array<database.DeviceUtilizationTrend>>;

export function GetHistoryData(arg1:number,arg2:string,arg3:string,arg4:number,arg5:number):Promise<main.HistoryDataResponse>;

export function GetHourlyOEE(arg1:Array<database.DeviceOEEConfig>):Promise<Array<database.HourlyOEE>>;

export function GetHourlyProduction(arg1:any):Promise<Array<database.HourlyProduction>>;

export function GetHourlyProductionAccurate(arg1:Array<database.DeviceVarConfig>):Promise<Array<database.HourlyProductionAccurate>>;

export function GetKnowledgeList():Promise<main.KnowledgeListResponse>;

export function GetMonthlyDailyQualityTrend():Promise<Array<database.DailyQualityTrend>>;

export function GetMonthlyProductionAccurate(arg1:Array<database.DeviceVarConfig>):Promise<Array<database.MonthlyProductionAccurate>>;

export function GetMonthlyQualityByOrder():Promise<Array<database.DeviceQualityStat>>;

export function GetProductionCoefficient():Promise<number>;

export function GetProductionCoefficientFromEnv():Promise<number>;

export function GetRealHourlyProduction():Promise<Array<database.HourlyProductionPulse>>;

export function GetRealtimeData():Promise<Array<main.TagData>>;

export function GetSessionHistory(arg1:any,arg2:any,arg3:string,arg4:string):Promise<Array<models.ProMachineSession>>;

export function GetSessionStats(arg1:number):Promise<models.SessionStatusResponse>;

export function GetStaffAttendance(arg1:number,arg2:string,arg3:string):Promise<Array<models.ProMachineSession>>;

export function GetStaffEfficiency(arg1:time.Time,arg2:time.Time):Promise<Array<database.StaffEfficiency>>;

export function GetStaffHistory(arg1:number):Promise<Array<models.SysStaffHistory>>;

export function GetSystemConfig():Promise<main.UserConfig>;

export function GetSystemMonitor():Promise<Record<string, any>>;

export function GetTodayEnergyConsumption(arg1:number):Promise<number>;

export function GetTodayHourlyAlarmCount():Promise<Array<main.HourlyAlarmCount>>;

export function GetTodayUnacknowledgedAlarmCount():Promise<number>;

export function GetVariableOptions():Promise<Array<main.VariableOption>>;

export function LikeAIAnswer(arg1:string,arg2:string,arg3:Array<main.RelevantDoc>):Promise<void>;

export function QueryAI(arg1:string):Promise<main.AIQueryResponse>;

export function QueryAIStream(arg1:string):Promise<void>;

export function QueryAIStreamWithQueue(arg1:string):Promise<void>;

export function SetBreakTimes(arg1:Array<main.BreakTime>):Promise<void>;

export function SetDailyWorkMinutes(arg1:number):Promise<void>;

export function SetProductionCoefficient(arg1:number):Promise<void>;

export function SetSystemConfig(arg1:main.UserConfig):Promise<void>;

export function StartProductionSmart(arg1:number):Promise<models.ProProductionRun>;

export function StopAIStream():Promise<boolean>;

export function SyncErrorCode(arg1:number,arg2:string):Promise<void>;

export function TransferStaff(arg1:number,arg2:number,arg3:any):Promise<void>;

export function TriggerTaskManually(arg1:number):Promise<void>;

export function UpdateOrder(arg1:number,arg2:any,arg3:any,arg4:any,arg5:any):Promise<void>;

export function UpdateStaff(arg1:number,arg2:any,arg3:any,arg4:any):Promise<void>;

export function UpdateTask(arg1:number,arg2:models.Task):Promise<void>;

export function UpdateTeam(arg1:number,arg2:any,arg3:any,arg4:any):Promise<void>;

export function UpdateVariable(arg1:database.VariableRow):Promise<void>;
